// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/order (interfaces: OrderRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_order_repo.go -package=mocks . OrderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	order "github.com/tharunn0/E-Commerce-Go/internal/domain/order"
	payment "github.com/tharunn0/E-Commerce-Go/internal/domain/payment"
	shipping "github.com/tharunn0/E-Commerce-Go/internal/domain/shipping"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderRepository) CancelOrder(ctx context.Context, orderID, reason string, orderItemsID []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, orderID, reason, orderItemsID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderRepositoryMockRecorder) CancelOrder(ctx, orderID, reason, orderItemsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderRepository)(nil).CancelOrder), ctx, orderID, reason, orderItemsID)
}

// CancelOrderNew mocks base method.
func (m *MockOrderRepository) CancelOrderNew(ctx context.Context, orderID, reason string, orderItemsID []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrderNew", ctx, orderID, reason, orderItemsID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrderNew indicates an expected call of CancelOrderNew.
func (mr *MockOrderRepositoryMockRecorder) CancelOrderNew(ctx, orderID, reason, orderItemsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrderNew", reflect.TypeOf((*MockOrderRepository)(nil).CancelOrderNew), ctx, orderID, reason, orderItemsID)
}

// CreateOrder mocks base method.
func (m *MockOrderRepository) CreateOrder(ctx context.Context, data *order.CreateOrderData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateOrder(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrder), ctx, data)
}

// DeliverOrder mocks base method.
func (m *MockOrderRepository) DeliverOrder(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliverOrder", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeliverOrder indicates an expected call of DeliverOrder.
func (mr *MockOrderRepositoryMockRecorder) DeliverOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliverOrder", reflect.TypeOf((*MockOrderRepository)(nil).DeliverOrder), ctx, orderID)
}

// GetReturnRequest mocks base method.
func (m *MockOrderRepository) GetReturnRequest(ctx context.Context, returnID int64) (*order.FullReturnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReturnRequest", ctx, returnID)
	ret0, _ := ret[0].(*order.FullReturnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReturnRequest indicates an expected call of GetReturnRequest.
func (mr *MockOrderRepositoryMockRecorder) GetReturnRequest(ctx, returnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReturnRequest", reflect.TypeOf((*MockOrderRepository)(nil).GetReturnRequest), ctx, returnID)
}

// GetUserOrderByID mocks base method.
func (m *MockOrderRepository) GetUserOrderByID(ctx context.Context, orderID string, userID int64) (*order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrderByID", ctx, orderID, userID)
	ret0, _ := ret[0].(*order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrderByID indicates an expected call of GetUserOrderByID.
func (mr *MockOrderRepositoryMockRecorder) GetUserOrderByID(ctx, orderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrderByID", reflect.TypeOf((*MockOrderRepository)(nil).GetUserOrderByID), ctx, orderID, userID)
}

// GetUserOrders mocks base method.
func (m *MockOrderRepository) GetUserOrders(ctx context.Context, userID int64) ([]order.OrderBaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx, userID)
	ret0, _ := ret[0].([]order.OrderBaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrderRepositoryMockRecorder) GetUserOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetUserOrders), ctx, userID)
}

// ListAllOrders mocks base method.
func (m *MockOrderRepository) ListAllOrders(ctx context.Context, filter *order.OrderFilter) ([]order.OrderBaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllOrders", ctx, filter)
	ret0, _ := ret[0].([]order.OrderBaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllOrders indicates an expected call of ListAllOrders.
func (mr *MockOrderRepositoryMockRecorder) ListAllOrders(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllOrders", reflect.TypeOf((*MockOrderRepository)(nil).ListAllOrders), ctx, filter)
}

// ListAllReturns mocks base method.
func (m *MockOrderRepository) ListAllReturns(ctx context.Context, filter *order.ReturnFilter) ([]order.BaseReturnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllReturns", ctx, filter)
	ret0, _ := ret[0].([]order.BaseReturnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllReturns indicates an expected call of ListAllReturns.
func (mr *MockOrderRepositoryMockRecorder) ListAllReturns(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllReturns", reflect.TypeOf((*MockOrderRepository)(nil).ListAllReturns), ctx, filter)
}

// ProcessReturnRefund mocks base method.
func (m *MockOrderRepository) ProcessReturnRefund(ctx context.Context, req *order.UpdateReturnRefundRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessReturnRefund", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessReturnRefund indicates an expected call of ProcessReturnRefund.
func (mr *MockOrderRepositoryMockRecorder) ProcessReturnRefund(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessReturnRefund", reflect.TypeOf((*MockOrderRepository)(nil).ProcessReturnRefund), ctx, req)
}

// ReturnOrderItemRequest mocks base method.
func (m *MockOrderRepository) ReturnOrderItemRequest(ctx context.Context, orderID string, userID, itemID int64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnOrderItemRequest", ctx, orderID, userID, itemID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReturnOrderItemRequest indicates an expected call of ReturnOrderItemRequest.
func (mr *MockOrderRepositoryMockRecorder) ReturnOrderItemRequest(ctx, orderID, userID, itemID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnOrderItemRequest", reflect.TypeOf((*MockOrderRepository)(nil).ReturnOrderItemRequest), ctx, orderID, userID, itemID, reason)
}

// ReturnOrderRequest mocks base method.
func (m *MockOrderRepository) ReturnOrderRequest(ctx context.Context, orderID string, userID int64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnOrderRequest", ctx, orderID, userID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReturnOrderRequest indicates an expected call of ReturnOrderRequest.
func (mr *MockOrderRepositoryMockRecorder) ReturnOrderRequest(ctx, orderID, userID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnOrderRequest", reflect.TypeOf((*MockOrderRepository)(nil).ReturnOrderRequest), ctx, orderID, userID, reason)
}

// ShipOrder mocks base method.
func (m *MockOrderRepository) ShipOrder(ctx context.Context, orderID string, shipmentData *shipping.ShipmentData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShipOrder", ctx, orderID, shipmentData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShipOrder indicates an expected call of ShipOrder.
func (mr *MockOrderRepositoryMockRecorder) ShipOrder(ctx, orderID, shipmentData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShipOrder", reflect.TypeOf((*MockOrderRepository)(nil).ShipOrder), ctx, orderID, shipmentData)
}

// UpdateOrderStatusOnPayment mocks base method.
func (m *MockOrderRepository) UpdateOrderStatusOnPayment(ctx context.Context, orderID string, status payment.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusOnPayment", ctx, orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatusOnPayment indicates an expected call of UpdateOrderStatusOnPayment.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderStatusOnPayment(ctx, orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusOnPayment", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderStatusOnPayment), ctx, orderID, status)
}

// UpdateReturnRequestStatus mocks base method.
func (m *MockOrderRepository) UpdateReturnRequestStatus(ctx context.Context, req *order.UpdateReturnRefundRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReturnRequestStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReturnRequestStatus indicates an expected call of UpdateReturnRequestStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateReturnRequestStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReturnRequestStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateReturnRequestStatus), ctx, req)
}

// UpdateShipmentStatus mocks base method.
func (m *MockOrderRepository) UpdateShipmentStatus(ctx context.Context, orderID string, status shipping.ShipmentStatus, cod bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShipmentStatus", ctx, orderID, status, cod)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShipmentStatus indicates an expected call of UpdateShipmentStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateShipmentStatus(ctx, orderID, status, cod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShipmentStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateShipmentStatus), ctx, orderID, status, cod)
}
