// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/promotion (interfaces: CouponRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_coupon_repo.go -package=mocks . CouponRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	promotion "github.com/tharunn0/E-Commerce-Go/internal/domain/promotion"
	gomock "go.uber.org/mock/gomock"
)

// MockCouponRepository is a mock of CouponRepository interface.
type MockCouponRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCouponRepositoryMockRecorder
	isgomock struct{}
}

// MockCouponRepositoryMockRecorder is the mock recorder for MockCouponRepository.
type MockCouponRepositoryMockRecorder struct {
	mock *MockCouponRepository
}

// NewMockCouponRepository creates a new mock instance.
func NewMockCouponRepository(ctrl *gomock.Controller) *MockCouponRepository {
	mock := &MockCouponRepository{ctrl: ctrl}
	mock.recorder = &MockCouponRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouponRepository) EXPECT() *MockCouponRepositoryMockRecorder {
	return m.recorder
}

// CreateCoupon mocks base method.
func (m *MockCouponRepository) CreateCoupon(ctx context.Context, req *promotion.CreateCouponRequest) (*promotion.CouponResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoupon", ctx, req)
	ret0, _ := ret[0].(*promotion.CouponResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCoupon indicates an expected call of CreateCoupon.
func (mr *MockCouponRepositoryMockRecorder) CreateCoupon(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoupon", reflect.TypeOf((*MockCouponRepository)(nil).CreateCoupon), ctx, req)
}

// FetchCoupon mocks base method.
func (m *MockCouponRepository) FetchCoupon(ctx context.Context, couponCode string, userID int64) (*promotion.CouponResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCoupon", ctx, couponCode, userID)
	ret0, _ := ret[0].(*promotion.CouponResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCoupon indicates an expected call of FetchCoupon.
func (mr *MockCouponRepositoryMockRecorder) FetchCoupon(ctx, couponCode, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCoupon", reflect.TypeOf((*MockCouponRepository)(nil).FetchCoupon), ctx, couponCode, userID)
}

// FetchCouponByID mocks base method.
func (m *MockCouponRepository) FetchCouponByID(ctx context.Context, couponID int64) (*promotion.CouponResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCouponByID", ctx, couponID)
	ret0, _ := ret[0].(*promotion.CouponResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCouponByID indicates an expected call of FetchCouponByID.
func (mr *MockCouponRepositoryMockRecorder) FetchCouponByID(ctx, couponID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCouponByID", reflect.TypeOf((*MockCouponRepository)(nil).FetchCouponByID), ctx, couponID)
}

// ListAllCoupons mocks base method.
func (m *MockCouponRepository) ListAllCoupons(ctx context.Context, filter *promotion.ListCouponsFilter) ([]promotion.CouponResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCoupons", ctx, filter)
	ret0, _ := ret[0].([]promotion.CouponResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllCoupons indicates an expected call of ListAllCoupons.
func (mr *MockCouponRepositoryMockRecorder) ListAllCoupons(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCoupons", reflect.TypeOf((*MockCouponRepository)(nil).ListAllCoupons), ctx, filter)
}

// ListReferralRewards mocks base method.
func (m *MockCouponRepository) ListReferralRewards(ctx context.Context, userID int64) ([]promotion.CouponResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReferralRewards", ctx, userID)
	ret0, _ := ret[0].([]promotion.CouponResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReferralRewards indicates an expected call of ListReferralRewards.
func (mr *MockCouponRepositoryMockRecorder) ListReferralRewards(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReferralRewards", reflect.TypeOf((*MockCouponRepository)(nil).ListReferralRewards), ctx, userID)
}

// UpdateCoupon mocks base method.
func (m *MockCouponRepository) UpdateCoupon(ctx context.Context, req *promotion.UpdateCouponRequest) (*promotion.CouponResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCoupon", ctx, req)
	ret0, _ := ret[0].(*promotion.CouponResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCoupon indicates an expected call of UpdateCoupon.
func (mr *MockCouponRepositoryMockRecorder) UpdateCoupon(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCoupon", reflect.TypeOf((*MockCouponRepository)(nil).UpdateCoupon), ctx, req)
}
