// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/promotion (interfaces: OfferRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_offer_repo.go -package=mocks . OfferRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	promotion "github.com/tharunn0/E-Commerce-Go/internal/domain/promotion"
	gomock "go.uber.org/mock/gomock"
)

// MockOfferRepository is a mock of OfferRepository interface.
type MockOfferRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOfferRepositoryMockRecorder
	isgomock struct{}
}

// MockOfferRepositoryMockRecorder is the mock recorder for MockOfferRepository.
type MockOfferRepositoryMockRecorder struct {
	mock *MockOfferRepository
}

// NewMockOfferRepository creates a new mock instance.
func NewMockOfferRepository(ctrl *gomock.Controller) *MockOfferRepository {
	mock := &MockOfferRepository{ctrl: ctrl}
	mock.recorder = &MockOfferRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfferRepository) EXPECT() *MockOfferRepositoryMockRecorder {
	return m.recorder
}

// CreateOffer mocks base method.
func (m *MockOfferRepository) CreateOffer(ctx context.Context, req *promotion.CreateOfferRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOffer", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOffer indicates an expected call of CreateOffer.
func (mr *MockOfferRepositoryMockRecorder) CreateOffer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOffer", reflect.TypeOf((*MockOfferRepository)(nil).CreateOffer), ctx, req)
}

// GetAllActiveOffers mocks base method.
func (m *MockOfferRepository) GetAllActiveOffers(ctx context.Context, productIDs, categoryIDs []int64) ([]*promotion.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveOffers", ctx, productIDs, categoryIDs)
	ret0, _ := ret[0].([]*promotion.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveOffers indicates an expected call of GetAllActiveOffers.
func (mr *MockOfferRepositoryMockRecorder) GetAllActiveOffers(ctx, productIDs, categoryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveOffers", reflect.TypeOf((*MockOfferRepository)(nil).GetAllActiveOffers), ctx, productIDs, categoryIDs)
}
