services:

  web:
    build: .
    ports: 
      - "3030:8080"
    env_file:
      - .env
    depends_on:
      - postgresdb
      - redisdb

  postgresdb:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ecommerce"]
      interval: 3s
      timeout: 3s
      retries: 5

  redisdb:
    image: redis:latest

volumes:
  postgres_data:
