// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/cart (interfaces: CartRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cart_repo.go -package=mocks . CartRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cart "github.com/tharunn0/E-Commerce-Go/internal/domain/cart"
	gomock "go.uber.org/mock/gomock"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
	isgomock struct{}
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// AddToCart mocks base method.
func (m *MockCartRepository) AddToCart(ctx context.Context, userID, productVariantID, quantity int64) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCart", ctx, userID, productVariantID, quantity)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToCart indicates an expected call of AddToCart.
func (mr *MockCartRepositoryMockRecorder) AddToCart(ctx, userID, productVariantID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCart", reflect.TypeOf((*MockCartRepository)(nil).AddToCart), ctx, userID, productVariantID, quantity)
}

// EmptyCart mocks base method.
func (m *MockCartRepository) EmptyCart(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmptyCart", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmptyCart indicates an expected call of EmptyCart.
func (mr *MockCartRepositoryMockRecorder) EmptyCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmptyCart", reflect.TypeOf((*MockCartRepository)(nil).EmptyCart), ctx, userID)
}

// GetCartByID mocks base method.
func (m *MockCartRepository) GetCartByID(ctx context.Context, cartID int64) (*cart.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByID", ctx, cartID)
	ret0, _ := ret[0].(*cart.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByID indicates an expected call of GetCartByID.
func (mr *MockCartRepositoryMockRecorder) GetCartByID(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByID", reflect.TypeOf((*MockCartRepository)(nil).GetCartByID), ctx, cartID)
}

// GetCartByUserID mocks base method.
func (m *MockCartRepository) GetCartByUserID(ctx context.Context, userID int64) (*cart.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserID", ctx, userID)
	ret0, _ := ret[0].(*cart.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserID indicates an expected call of GetCartByUserID.
func (mr *MockCartRepositoryMockRecorder) GetCartByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserID", reflect.TypeOf((*MockCartRepository)(nil).GetCartByUserID), ctx, userID)
}

// GetCartVariantInfo mocks base method.
func (m *MockCartRepository) GetCartVariantInfo(ctx context.Context, userID int64) (map[int64]cart.VariantInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartVariantInfo", ctx, userID)
	ret0, _ := ret[0].(map[int64]cart.VariantInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartVariantInfo indicates an expected call of GetCartVariantInfo.
func (mr *MockCartRepositoryMockRecorder) GetCartVariantInfo(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartVariantInfo", reflect.TypeOf((*MockCartRepository)(nil).GetCartVariantInfo), ctx, userID)
}

// RemoveCartItem mocks base method.
func (m *MockCartRepository) RemoveCartItem(ctx context.Context, userID, productVariantID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCartItem", ctx, userID, productVariantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCartItem indicates an expected call of RemoveCartItem.
func (mr *MockCartRepositoryMockRecorder) RemoveCartItem(ctx, userID, productVariantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCartItem", reflect.TypeOf((*MockCartRepository)(nil).RemoveCartItem), ctx, userID, productVariantID)
}

// UpdateCartItemQuantity mocks base method.
func (m *MockCartRepository) UpdateCartItemQuantity(ctx context.Context, userID int64, req *cart.UpdateCartItemQuantityRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItemQuantity", ctx, userID, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItemQuantity indicates an expected call of UpdateCartItemQuantity.
func (mr *MockCartRepositoryMockRecorder) UpdateCartItemQuantity(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItemQuantity", reflect.TypeOf((*MockCartRepository)(nil).UpdateCartItemQuantity), ctx, userID, req)
}
