// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/product (interfaces: ProductRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_product_repo.go -package=mocks . ProductRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	product "github.com/tharunn0/E-Commerce-Go/internal/domain/product"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// AddAttributeValues mocks base method.
func (m *MockProductRepository) AddAttributeValues(ctx context.Context, attributeValues *product.AddAttributeValuesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAttributeValues", ctx, attributeValues)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAttributeValues indicates an expected call of AddAttributeValues.
func (mr *MockProductRepositoryMockRecorder) AddAttributeValues(ctx, attributeValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAttributeValues", reflect.TypeOf((*MockProductRepository)(nil).AddAttributeValues), ctx, attributeValues)
}

// CreateAttribute mocks base method.
func (m *MockProductRepository) CreateAttribute(ctx context.Context, attribute *product.CreateAttributeRequest) (*product.Attribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttribute", ctx, attribute)
	ret0, _ := ret[0].(*product.Attribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttribute indicates an expected call of CreateAttribute.
func (mr *MockProductRepositoryMockRecorder) CreateAttribute(ctx, attribute any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttribute", reflect.TypeOf((*MockProductRepository)(nil).CreateAttribute), ctx, attribute)
}

// CreateBrand mocks base method.
func (m *MockProductRepository) CreateBrand(ctx context.Context, createBrandRequest *product.CreateBrandRequest) (*product.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBrand", ctx, createBrandRequest)
	ret0, _ := ret[0].(*product.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBrand indicates an expected call of CreateBrand.
func (mr *MockProductRepositoryMockRecorder) CreateBrand(ctx, createBrandRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBrand", reflect.TypeOf((*MockProductRepository)(nil).CreateBrand), ctx, createBrandRequest)
}

// CreateProduct mocks base method.
func (m *MockProductRepository) CreateProduct(ctx context.Context, arg1 *product.CreateProductRequest) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, arg1)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductRepositoryMockRecorder) CreateProduct(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductRepository)(nil).CreateProduct), ctx, arg1)
}

// CreateProductVariant mocks base method.
func (m *MockProductRepository) CreateProductVariant(ctx context.Context, productVariant *product.CreateProductVariantRequest) (*product.ProductVariantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductVariant", ctx, productVariant)
	ret0, _ := ret[0].(*product.ProductVariantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductVariant indicates an expected call of CreateProductVariant.
func (mr *MockProductRepositoryMockRecorder) CreateProductVariant(ctx, productVariant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductVariant", reflect.TypeOf((*MockProductRepository)(nil).CreateProductVariant), ctx, productVariant)
}

// DeleteAttribute mocks base method.
func (m *MockProductRepository) DeleteAttribute(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttribute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttribute indicates an expected call of DeleteAttribute.
func (mr *MockProductRepositoryMockRecorder) DeleteAttribute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttribute", reflect.TypeOf((*MockProductRepository)(nil).DeleteAttribute), ctx, id)
}

// DeleteAttributeValues mocks base method.
func (m *MockProductRepository) DeleteAttributeValues(ctx context.Context, req *product.DeleteAttributeValuesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttributeValues", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttributeValues indicates an expected call of DeleteAttributeValues.
func (mr *MockProductRepositoryMockRecorder) DeleteAttributeValues(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttributeValues", reflect.TypeOf((*MockProductRepository)(nil).DeleteAttributeValues), ctx, req)
}

// DeleteBrand mocks base method.
func (m *MockProductRepository) DeleteBrand(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBrand", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBrand indicates an expected call of DeleteBrand.
func (mr *MockProductRepositoryMockRecorder) DeleteBrand(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBrand", reflect.TypeOf((*MockProductRepository)(nil).DeleteBrand), ctx, id)
}

// DeleteProduct mocks base method.
func (m *MockProductRepository) DeleteProduct(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductRepositoryMockRecorder) DeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductRepository)(nil).DeleteProduct), ctx, id)
}

// DeleteProductVariant mocks base method.
func (m *MockProductRepository) DeleteProductVariant(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductVariant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductVariant indicates an expected call of DeleteProductVariant.
func (mr *MockProductRepositoryMockRecorder) DeleteProductVariant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductVariant", reflect.TypeOf((*MockProductRepository)(nil).DeleteProductVariant), ctx, id)
}

// GetAllBrands mocks base method.
func (m *MockProductRepository) GetAllBrands(ctx context.Context, activeOnly bool) ([]*product.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBrands", ctx, activeOnly)
	ret0, _ := ret[0].([]*product.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBrands indicates an expected call of GetAllBrands.
func (mr *MockProductRepositoryMockRecorder) GetAllBrands(ctx, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBrands", reflect.TypeOf((*MockProductRepository)(nil).GetAllBrands), ctx, activeOnly)
}

// GetAttributeByID mocks base method.
func (m *MockProductRepository) GetAttributeByID(ctx context.Context, id int64, activeOnly bool) (*product.Attribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeByID", ctx, id, activeOnly)
	ret0, _ := ret[0].(*product.Attribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeByID indicates an expected call of GetAttributeByID.
func (mr *MockProductRepositoryMockRecorder) GetAttributeByID(ctx, id, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeByID", reflect.TypeOf((*MockProductRepository)(nil).GetAttributeByID), ctx, id, activeOnly)
}

// GetAttributes mocks base method.
func (m *MockProductRepository) GetAttributes(ctx context.Context, activeOnly bool) ([]*product.Attribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributes", ctx, activeOnly)
	ret0, _ := ret[0].([]*product.Attribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributes indicates an expected call of GetAttributes.
func (mr *MockProductRepositoryMockRecorder) GetAttributes(ctx, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributes", reflect.TypeOf((*MockProductRepository)(nil).GetAttributes), ctx, activeOnly)
}

// GetBrandByID mocks base method.
func (m *MockProductRepository) GetBrandByID(ctx context.Context, id int64, activeOnly bool) (*product.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrandByID", ctx, id, activeOnly)
	ret0, _ := ret[0].(*product.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrandByID indicates an expected call of GetBrandByID.
func (mr *MockProductRepositoryMockRecorder) GetBrandByID(ctx, id, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrandByID", reflect.TypeOf((*MockProductRepository)(nil).GetBrandByID), ctx, id, activeOnly)
}

// GetProductByID mocks base method.
func (m *MockProductRepository) GetProductByID(ctx context.Context, id int64, activeOnly bool) (*product.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id, activeOnly)
	ret0, _ := ret[0].(*product.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductRepositoryMockRecorder) GetProductByID(ctx, id, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductRepository)(nil).GetProductByID), ctx, id, activeOnly)
}

// GetProductVariantByID mocks base method.
func (m *MockProductRepository) GetProductVariantByID(ctx context.Context, id int64, activeOnly bool) (*product.ProductVariantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductVariantByID", ctx, id, activeOnly)
	ret0, _ := ret[0].(*product.ProductVariantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductVariantByID indicates an expected call of GetProductVariantByID.
func (mr *MockProductRepositoryMockRecorder) GetProductVariantByID(ctx, id, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductVariantByID", reflect.TypeOf((*MockProductRepository)(nil).GetProductVariantByID), ctx, id, activeOnly)
}

// GetProductVariantOrderInfo mocks base method.
func (m *MockProductRepository) GetProductVariantOrderInfo(ctx context.Context, productVariantID int64) (*product.VariantOrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductVariantOrderInfo", ctx, productVariantID)
	ret0, _ := ret[0].(*product.VariantOrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductVariantOrderInfo indicates an expected call of GetProductVariantOrderInfo.
func (mr *MockProductRepositoryMockRecorder) GetProductVariantOrderInfo(ctx, productVariantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductVariantOrderInfo", reflect.TypeOf((*MockProductRepository)(nil).GetProductVariantOrderInfo), ctx, productVariantID)
}

// GetProducts mocks base method.
func (m *MockProductRepository) GetProducts(ctx context.Context, filter *product.ProductFilter, activeOnly bool) ([]*product.ProductResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx, filter, activeOnly)
	ret0, _ := ret[0].([]*product.ProductResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockProductRepositoryMockRecorder) GetProducts(ctx, filter, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockProductRepository)(nil).GetProducts), ctx, filter, activeOnly)
}

// GetVariantsByProductID mocks base method.
func (m *MockProductRepository) GetVariantsByProductID(ctx context.Context, productID int64, activeOnly bool) (*product.ProductVariantBaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariantsByProductID", ctx, productID, activeOnly)
	ret0, _ := ret[0].(*product.ProductVariantBaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariantsByProductID indicates an expected call of GetVariantsByProductID.
func (mr *MockProductRepositoryMockRecorder) GetVariantsByProductID(ctx, productID, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariantsByProductID", reflect.TypeOf((*MockProductRepository)(nil).GetVariantsByProductID), ctx, productID, activeOnly)
}

// ToggleProductStatus mocks base method.
func (m *MockProductRepository) ToggleProductStatus(ctx context.Context, req *product.ProductStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleProductStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleProductStatus indicates an expected call of ToggleProductStatus.
func (mr *MockProductRepositoryMockRecorder) ToggleProductStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleProductStatus", reflect.TypeOf((*MockProductRepository)(nil).ToggleProductStatus), ctx, req)
}

// ToggleVariantStatus mocks base method.
func (m *MockProductRepository) ToggleVariantStatus(ctx context.Context, req *product.VariantStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleVariantStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleVariantStatus indicates an expected call of ToggleVariantStatus.
func (mr *MockProductRepositoryMockRecorder) ToggleVariantStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleVariantStatus", reflect.TypeOf((*MockProductRepository)(nil).ToggleVariantStatus), ctx, req)
}

// UpdateBrand mocks base method.
func (m *MockProductRepository) UpdateBrand(ctx context.Context, brand *product.Brand) (*product.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBrand", ctx, brand)
	ret0, _ := ret[0].(*product.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBrand indicates an expected call of UpdateBrand.
func (mr *MockProductRepositoryMockRecorder) UpdateBrand(ctx, brand any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBrand", reflect.TypeOf((*MockProductRepository)(nil).UpdateBrand), ctx, brand)
}

// UpdateProduct mocks base method.
func (m *MockProductRepository) UpdateProduct(ctx context.Context, updateProductRequest *product.UpdateProductRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, updateProductRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductRepositoryMockRecorder) UpdateProduct(ctx, updateProductRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductRepository)(nil).UpdateProduct), ctx, updateProductRequest)
}

// UpdateProductMinMaxPrice mocks base method.
func (m *MockProductRepository) UpdateProductMinMaxPrice(ctx context.Context, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductMinMaxPrice", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductMinMaxPrice indicates an expected call of UpdateProductMinMaxPrice.
func (mr *MockProductRepositoryMockRecorder) UpdateProductMinMaxPrice(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductMinMaxPrice", reflect.TypeOf((*MockProductRepository)(nil).UpdateProductMinMaxPrice), ctx, productID)
}

// UpdateProductVariant mocks base method.
func (m *MockProductRepository) UpdateProductVariant(ctx context.Context, productVariant *product.UpdateProductVariantRequest) (*product.ProductVariant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductVariant", ctx, productVariant)
	ret0, _ := ret[0].(*product.ProductVariant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProductVariant indicates an expected call of UpdateProductVariant.
func (mr *MockProductRepositoryMockRecorder) UpdateProductVariant(ctx, productVariant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductVariant", reflect.TypeOf((*MockProductRepository)(nil).UpdateProductVariant), ctx, productVariant)
}
