// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/user (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_user_repo.go -package=mocks . UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	payment "github.com/tharunn0/E-Commerce-Go/internal/domain/payment"
	user "github.com/tharunn0/E-Commerce-Go/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// DeleteUserAddress mocks base method.
func (m *MockUserRepository) DeleteUserAddress(ctx context.Context, userID, addressID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAddress", ctx, userID, addressID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAddress indicates an expected call of DeleteUserAddress.
func (mr *MockUserRepositoryMockRecorder) DeleteUserAddress(ctx, userID, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAddress", reflect.TypeOf((*MockUserRepository)(nil).DeleteUserAddress), ctx, userID, addressID)
}

// GetDefaultUserAddress mocks base method.
func (m *MockUserRepository) GetDefaultUserAddress(ctx context.Context, userID int64) (*user.UserAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultUserAddress", ctx, userID)
	ret0, _ := ret[0].(*user.UserAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultUserAddress indicates an expected call of GetDefaultUserAddress.
func (mr *MockUserRepositoryMockRecorder) GetDefaultUserAddress(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultUserAddress", reflect.TypeOf((*MockUserRepository)(nil).GetDefaultUserAddress), ctx, userID)
}

// GetUser mocks base method.
func (m *MockUserRepository) GetUser(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserRepositoryMockRecorder) GetUser(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserRepository)(nil).GetUser), ctx, email)
}

// GetUserAddressByID mocks base method.
func (m *MockUserRepository) GetUserAddressByID(ctx context.Context, addressID int64) (*user.UserAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAddressByID", ctx, addressID)
	ret0, _ := ret[0].(*user.UserAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAddressByID indicates an expected call of GetUserAddressByID.
func (mr *MockUserRepositoryMockRecorder) GetUserAddressByID(ctx, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAddressByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserAddressByID), ctx, addressID)
}

// GetUserAddresses mocks base method.
func (m *MockUserRepository) GetUserAddresses(ctx context.Context, userID int64) ([]*user.UserAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAddresses", ctx, userID)
	ret0, _ := ret[0].([]*user.UserAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAddresses indicates an expected call of GetUserAddresses.
func (mr *MockUserRepositoryMockRecorder) GetUserAddresses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAddresses", reflect.TypeOf((*MockUserRepository)(nil).GetUserAddresses), ctx, userID)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID int64) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// GetWallet mocks base method.
func (m *MockUserRepository) GetWallet(ctx context.Context, userID int64) (*payment.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallet", ctx, userID)
	ret0, _ := ret[0].(*payment.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWallet indicates an expected call of GetWallet.
func (mr *MockUserRepositoryMockRecorder) GetWallet(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallet", reflect.TypeOf((*MockUserRepository)(nil).GetWallet), ctx, userID)
}

// GetWalletTransactions mocks base method.
func (m *MockUserRepository) GetWalletTransactions(ctx context.Context, userID int64, filter *payment.TransactionFilter) ([]*payment.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletTransactions", ctx, userID, filter)
	ret0, _ := ret[0].([]*payment.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletTransactions indicates an expected call of GetWalletTransactions.
func (mr *MockUserRepositoryMockRecorder) GetWalletTransactions(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletTransactions", reflect.TypeOf((*MockUserRepository)(nil).GetWalletTransactions), ctx, userID, filter)
}

// GoogleSignIn mocks base method.
func (m *MockUserRepository) GoogleSignIn(ctx context.Context, req *user.GoogleSignInRequest) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleSignIn", ctx, req)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoogleSignIn indicates an expected call of GoogleSignIn.
func (mr *MockUserRepositoryMockRecorder) GoogleSignIn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleSignIn", reflect.TypeOf((*MockUserRepository)(nil).GoogleSignIn), ctx, req)
}

// InsertUserAddress mocks base method.
func (m *MockUserRepository) InsertUserAddress(ctx context.Context, address *user.UserAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUserAddress", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUserAddress indicates an expected call of InsertUserAddress.
func (mr *MockUserRepositoryMockRecorder) InsertUserAddress(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUserAddress", reflect.TypeOf((*MockUserRepository)(nil).InsertUserAddress), ctx, address)
}

// RegisterUser mocks base method.
func (m *MockUserRepository) RegisterUser(ctx context.Context, req *user.RegisterRequest, refCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, req, refCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserRepositoryMockRecorder) RegisterUser(ctx, req, refCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserRepository)(nil).RegisterUser), ctx, req, refCode)
}

// UpdateDefaultUserAddress mocks base method.
func (m *MockUserRepository) UpdateDefaultUserAddress(ctx context.Context, userID, addressID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDefaultUserAddress", ctx, userID, addressID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDefaultUserAddress indicates an expected call of UpdateDefaultUserAddress.
func (mr *MockUserRepositoryMockRecorder) UpdateDefaultUserAddress(ctx, userID, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDefaultUserAddress", reflect.TypeOf((*MockUserRepository)(nil).UpdateDefaultUserAddress), ctx, userID, addressID)
}

// UpdateUserAddress mocks base method.
func (m *MockUserRepository) UpdateUserAddress(ctx context.Context, userID int64, req *user.UpdateUserAddressRequest) (*user.UserAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAddress", ctx, userID, req)
	ret0, _ := ret[0].(*user.UserAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserAddress indicates an expected call of UpdateUserAddress.
func (mr *MockUserRepositoryMockRecorder) UpdateUserAddress(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAddress", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserAddress), ctx, userID, req)
}

// UpdateUserProfile mocks base method.
func (m *MockUserRepository) UpdateUserProfile(ctx context.Context, userID int64, req *user.UpdateUserProfileRequest) (*user.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, userID, req)
	ret0, _ := ret[0].(*user.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserRepositoryMockRecorder) UpdateUserProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserProfile), ctx, userID, req)
}
