// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/auth (interfaces: AuthRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_auth_repo.go -package=mocks . AuthRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	auth "github.com/tharunn0/E-Commerce-Go/internal/domain/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// GetEmailVerificationToken mocks base method.
func (m *MockAuthRepository) GetEmailVerificationToken(ctx context.Context, token string) (*auth.EmailVerificationTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailVerificationToken", ctx, token)
	ret0, _ := ret[0].(*auth.EmailVerificationTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailVerificationToken indicates an expected call of GetEmailVerificationToken.
func (mr *MockAuthRepositoryMockRecorder) GetEmailVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailVerificationToken", reflect.TypeOf((*MockAuthRepository)(nil).GetEmailVerificationToken), ctx, token)
}

// GetLatestOTP mocks base method.
func (m *MockAuthRepository) GetLatestOTP(email string) (*auth.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestOTP", email)
	ret0, _ := ret[0].(*auth.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestOTP indicates an expected call of GetLatestOTP.
func (mr *MockAuthRepositoryMockRecorder) GetLatestOTP(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestOTP", reflect.TypeOf((*MockAuthRepository)(nil).GetLatestOTP), email)
}

// GetPasswordResetToken mocks base method.
func (m *MockAuthRepository) GetPasswordResetToken(ctx context.Context, token string) (*auth.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordResetToken", ctx, token)
	ret0, _ := ret[0].(*auth.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordResetToken indicates an expected call of GetPasswordResetToken.
func (mr *MockAuthRepositoryMockRecorder) GetPasswordResetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordResetToken", reflect.TypeOf((*MockAuthRepository)(nil).GetPasswordResetToken), ctx, token)
}

// GetRefreshToken mocks base method.
func (m *MockAuthRepository) GetRefreshToken(ctx context.Context, token string) (*auth.RefreshToken, *auth.RefreshTokenUserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, token)
	ret0, _ := ret[0].(*auth.RefreshToken)
	ret1, _ := ret[1].(*auth.RefreshTokenUserData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) GetRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).GetRefreshToken), ctx, token)
}

// InsertOTP mocks base method.
func (m *MockAuthRepository) InsertOTP(ctx context.Context, otpdata *auth.OTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOTP", ctx, otpdata)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOTP indicates an expected call of InsertOTP.
func (mr *MockAuthRepositoryMockRecorder) InsertOTP(ctx, otpdata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOTP", reflect.TypeOf((*MockAuthRepository)(nil).InsertOTP), ctx, otpdata)
}

// MarkUserVerified mocks base method.
func (m *MockAuthRepository) MarkUserVerified(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUserVerified", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUserVerified indicates an expected call of MarkUserVerified.
func (mr *MockAuthRepositoryMockRecorder) MarkUserVerified(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUserVerified", reflect.TypeOf((*MockAuthRepository)(nil).MarkUserVerified), email)
}

// MarkVerified mocks base method.
func (m *MockAuthRepository) MarkVerified(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerified", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkVerified indicates an expected call of MarkVerified.
func (mr *MockAuthRepositoryMockRecorder) MarkVerified(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerified", reflect.TypeOf((*MockAuthRepository)(nil).MarkVerified), id)
}

// PasswordReset mocks base method.
func (m *MockAuthRepository) PasswordReset(ctx context.Context, req *auth.PasswordResetData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordReset", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// PasswordReset indicates an expected call of PasswordReset.
func (mr *MockAuthRepositoryMockRecorder) PasswordReset(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordReset", reflect.TypeOf((*MockAuthRepository)(nil).PasswordReset), ctx, req)
}

// RevokeRefreshToken mocks base method.
func (m *MockAuthRepository) RevokeRefreshToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) RevokeRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).RevokeRefreshToken), ctx, token)
}

// SetEmailVerificationToken mocks base method.
func (m *MockAuthRepository) SetEmailVerificationToken(ctx context.Context, req *auth.EmailVerificationTokenData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmailVerificationToken", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmailVerificationToken indicates an expected call of SetEmailVerificationToken.
func (mr *MockAuthRepositoryMockRecorder) SetEmailVerificationToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmailVerificationToken", reflect.TypeOf((*MockAuthRepository)(nil).SetEmailVerificationToken), ctx, req)
}

// SetPasswordResetToken mocks base method.
func (m *MockAuthRepository) SetPasswordResetToken(ctx context.Context, req *auth.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPasswordResetToken", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPasswordResetToken indicates an expected call of SetPasswordResetToken.
func (mr *MockAuthRepositoryMockRecorder) SetPasswordResetToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPasswordResetToken", reflect.TypeOf((*MockAuthRepository)(nil).SetPasswordResetToken), ctx, req)
}

// SetRefreshToken mocks base method.
func (m *MockAuthRepository) SetRefreshToken(ctx context.Context, req *auth.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefreshToken", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefreshToken indicates an expected call of SetRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) SetRefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).SetRefreshToken), ctx, req)
}

// UpdateEmail mocks base method.
func (m *MockAuthRepository) UpdateEmail(ctx context.Context, currentEmail string, req *auth.EmailVerificationTokenData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, currentEmail, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockAuthRepositoryMockRecorder) UpdateEmail(ctx, currentEmail, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockAuthRepository)(nil).UpdateEmail), ctx, currentEmail, req)
}

// UpdateOTP mocks base method.
func (m *MockAuthRepository) UpdateOTP(email, otp string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOTP", email, otp, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOTP indicates an expected call of UpdateOTP.
func (mr *MockAuthRepositoryMockRecorder) UpdateOTP(email, otp, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOTP", reflect.TypeOf((*MockAuthRepository)(nil).UpdateOTP), email, otp, expiresAt)
}
