// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tharunn0/E-Commerce-Go/internal/domain/payment (interfaces: PaymentRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_payment_repo.go -package=mocks . PaymentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	payment "github.com/tharunn0/E-Commerce-Go/internal/domain/payment"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentRepository) CreatePayment(ctx context.Context, arg1 *payment.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentRepositoryMockRecorder) CreatePayment(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentRepository)(nil).CreatePayment), ctx, arg1)
}

// UpdateOrderPaymentStatus mocks base method.
func (m *MockPaymentRepository) UpdateOrderPaymentStatus(ctx context.Context, orderID string, paymentData *payment.WebhookPayment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderPaymentStatus", ctx, orderID, paymentData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderPaymentStatus indicates an expected call of UpdateOrderPaymentStatus.
func (mr *MockPaymentRepositoryMockRecorder) UpdateOrderPaymentStatus(ctx, orderID, paymentData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderPaymentStatus", reflect.TypeOf((*MockPaymentRepository)(nil).UpdateOrderPaymentStatus), ctx, orderID, paymentData)
}

// UpdatePaymentStatus mocks base method.
func (m *MockPaymentRepository) UpdatePaymentStatus(ctx context.Context, orderID string, status payment.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockPaymentRepositoryMockRecorder) UpdatePaymentStatus(ctx, orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockPaymentRepository)(nil).UpdatePaymentStatus), ctx, orderID, status)
}
